name: Franek

localIP: 127.0.0.1
multicastIP: 224.1.1.54

multicastTTL: 1

udpPort: 7071
multicastPort: 8081
tcpPort: 9091

logConfig: logger2.conf

packetLength: 5000

timeToReceiveResponse: 1000

timeout: 2000