name: Franek

localIP: 127.0.0.1
multicastIP: 224.0.0.1

multicastTTL: 1

udpPort: 7071
multicastPort: 7897
tcpPort: 9091

logConfig: logger.conf

packetLength: 5000

timeToReceiveResponse: 1000

timeout: 2000