name: Franek2

localIP: 127.0.0.1
multicastIP: 224.0.0.1

multicastTTL: 1

udpPort: 7070
multicastPort: 7897
tcpPort: 9090

logConfig: logger2.conf

packetLength: 5000

timeToReceiveResponse: 1000

timeout: 2000